### ISSUE TITLE
Ubuntu 16.04 wifi and battery icons issue

### ISSUE THREAD

**Issue by yanike** [OrancheloTeam/oranchelo-icon-theme#31]
![image](https://user-images.githubusercontent.com/6353864/37909963-f5822f08-30d1-11e8-9b10-c2e5fdc96e19.png)

The WiFi and Battery icons on the panel bar are not displaying icons. Please fix :)

**Comment by srpatatas** [comment]
It's happening to me too in Ubuntu 16.04 after the last update, thanks!

**Comment by shankhadevpadam** [comment]
I also face same problem after latest update.

**Comment by NonnEmilia** [comment]
The same here on Ubuntu 16.04.4 LTS

Oranchelo:
![oranchelo-missing-bar-icons](https://user-images.githubusercontent.com/2818194/38750009-d318c914-3f53-11e8-99c8-f8e221033c2c.png)

Default (Ubuntu mono dark):
![oranchelo-bar-icons](https://user-images.githubusercontent.com/2818194/38750092-1ebc3248-3f54-11e8-905c-14a92c537908.png)

**Comment by zayronxio** [comment]
please try now

**Comment by yanike** [comment]
ok will do :)

**Comment by zayronxio** [comment]
direct download of the master,

**Comment by yanike** [comment]
Not seeing it fixed on my end.

**Comment by yanike** [comment]
The issue is that your links are broken for the icons. They seem to have a target for the sandbox computer.

![selection_006](https://user-images.githubusercontent.com/6353864/38905654-915ccc42-4277-11e8-8925-0d64a08d2372.png)

**Comment by yanike** [comment]
There are a lot of broken links.

**Comment by zayronxio** [comment]
apparently the error has been solved, I hope I could help with some confirmation

**Comment by shankhadevpadam** [comment]
Still not working in my system

**Comment by yanike** [comment]
You have to download the master and run the installer. The repo isn’t updated that I know of yet.

**Comment by shankhadevpadam** [comment]
Still missing wifi icon. After I have download the master and run the installer.

**Comment by zayronxio** [comment]
unfortunately I do not identify the problem, just download the latest version of Ubuntu 16.04 and the wifi icon if it appears, please try this latest version

**Comment by shankhadevpadam** [comment]
Now it's fixed in ubuntu 16.04 after latest update.
Thanks

**Comment by NonnEmilia** [comment]
Fixed also for me with 0.7.6.7 version
